name: premio_inn
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bottom_navy_bar: 6.0.0
  cached_network_image: ^3.2.2
  cupertino_icons: 1.0.2
  dio: 4.0.6
  flutter:
    sdk: flutter
  flutter_svg: 1.1.5
  fluttertoast: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  pin_code_fields: 7.4.0
  provider: 6.0.3
  razorpay_flutter: ^1.3.3
  shared_preferences: 2.0.15
  shimmer: 2.0.0
  smooth_page_indicator: 1.0.0+2

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MainFont
      fonts:
        - asset: assets/fonts/BubblegumSans-Regular.ttf

    - family: SubMainFont
      fonts:
        - asset: assets/fonts/Cabin-VariableFont_wdth,wght.ttf
